server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    register-with-eureka: true # true : ?? ? ??? ???? ??
    fetch-registry: true # true : ?? ? ??? ???? ??
    service-url:
      defalutZone: http://127.0.0.1:8761/eureka

